name: Publish to npm

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed to push changes back to repo

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed for npm version to work properly

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Updated to a current LTS version
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit updated package-lock.json if needed
        run: |
          git add package-lock.json
          git diff --cached --quiet || git commit -m "chore: update package-lock.json"

      - name: Bump version
        run: |
          npm version patch
          git push --follow-tags

      - name: Build TypeScript
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
